apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  namespace: jenkins-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      imagePullSecrets:
        - name: dockerhub-creds
      containers:
        - name: my-node-app
          image: jarvi18/my-node-app:latest   # <- change this image
          ports:
          - containerPort: 3000
      # If image is private, add imagePullSecrets: - name: regcred

